---
- name: upgrade packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: install python and pip
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-docker
    state: present
    update_cache: true

- name: check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: reboot if required
  ansible.builtin.reboot:
    reboot_timeout: 120
  when: reboot_required_file.stat.exists
