---
- name: add tailscale key
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    mode: 0644

- name: add tailscale repo
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list
    dest: /etc/apt/sources.list.d/tailscale.list
    mode: 0644

- name: install tailscale
  ansible.builtin.apt:
    name: tailscale
    update_cache: true
